image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SITE_PATH: manualeUtente

test:
  stage: test
  script:
    - apk update && apk add git
    - hugo -s $SITE_PATH
  # except:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: build
  script:
    - apk update && apk add git
    - hugo -s $SITE_PATH
    - mv $SITE_PATH/public . 
  artifacts:
    paths:
      - public
  # only:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH