image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SITE_PATH: manualeUtente

test:
  script:
    - hugo -s $SITE_PATH
  # except:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo -s $SITE_PATH
    - mkdir public 
    - mv $SITE_PATH/public public 
  artifacts:
    paths:
      - public
  # only:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
