image: registry.gitlab.com/pages/hugo:latest

stages:
  - test
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  WEBSITE_PATH: blockcovid

test_website:
  stage: test
  script:
    - apk update && apk add git
    - hugo -s $WEBSITE_PATH
  # except:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build_website:
  stage: build
  script:
    - apk update && apk add git
    - hugo -s $WEBSITE_PATH 
    - mv $WEBSITE_PATH/public public
  artifacts:
    paths:
      - public

pages:
  stage: publish
  script:
    - echo 'Publishing'
  artifacts:
    paths:
      - public
  # only:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
