image: node:16
stages:
  - test
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  WEBSITE_PATH: blockcovid

test_website:
  stage: test
  script:
    - cd $WEBSITE_PATH
    - npm i
    - npm run test
  allow_failure: true
  # except:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build_website:
  stage: build
  script:
    - cd $WEBSITE_PATH
    - npm i
    - npm run build
    - mv public ../public
  artifacts:
    paths:
      - public

pages:
  stage: publish
  script:
    - echo 'Publishing'
  artifacts:
    paths:
      - public
  # only:
  #   variables:
  #     - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
