apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: amqp-listener
      port: 5672
      targetPort: 5672
    - name: http-api
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
