apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-example-com
  annotations:
    konghq.com/plugins: kong-oidc,request-id
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80