[[docs]]
  name = "Prologo"
  weight = 10
  identifier = "prologo"
  url = "/docs/prologo/"

[[docs]]
  name = "Manuale utente"
  identifier = "manuale-utente"
  url = "/docs/manuale-utente"
  weight = 30

[[docs]]
  name = "Manuale sviluppatore"
  identifier = "manuale-sviluppatore"
  url = "/docs/manuale-sviluppatore"
  weight = 40

[[docs]]
  name = "Backend"
  identifier = "backend"
  url = "/docs/manuale-sviluppatore/backend"
  weight = 50

[[docs]]
  name = "App web"
  identifier = "web-app"
  url = "/docs/manuale-sviluppatore/web-app"
  weight = 60

[[docs]]
  name = "App mobile"
  identifier = "mobile-app"
  url = "/docs/manuale-sviluppatore/mobile-app"
  weight = 70


[[main]]
  name = "Docs"
  url = "/docs/prologo/introduzione/"
  weight = 10

[[main]]
  name = "Repos"
  url = "https://gitlab.com/sweleven/blockcovid"
  weight = 20

# [[main]]
#   name = "Manuale ut"
#   url = "/docs/manuale-utente/"
#   weight = 30

# [[main]]
#   name = "Manuale svil"
#   url = "/docs/manuale-sviluppatore/"
#   weight = 40


[[social]]
  name = "GitLab"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://gitlab.com/sweleven"
  post = "v0.1.0"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
