version: '3.7'

services:
  # Blockchain simulator
  ganache-cli:
    build:
      dockerfile: dockerfile
      context: ../ganache-cli
    volumes:
      - ganache-volume:/ganache-data
    ports:
      - 8545:8545
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: "loki:3100/loki/api/v1/push"

  message-broker:
    build:
      dockerfile: dockerfile
      context: ../message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  # Blockchain-interactor microservice
  blockchain-interactor:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../blockchain-interactor
    volumes:
      - ../blockchain-interactor:/app
    ports:
      - "9231:9231"
      - "3001:3001"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"

  blockchain-interactor-data-persistence:
    build:
      dockerfile: dockerfile
      context: ../data-persistence
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=blockcovid
    volumes:
      - blockchain-interactor-mongo-volume:/data/db
    ports:
      - "27017:27017"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"



  # API Gateway
  api-gateway:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../api-gateway-dummy
    volumes:
      - ../api-gateway-dummy:/app
    ports:
      - "9230:9230"
      - "3000:3000"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"


  # Web Interface
  web-interface:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../web-interface
    volumes:
      - ../web-interface/:/app/
    ports:
      - "4200:4200"

volumes:
  blockchain-interactor-mongo-volume:
    driver: local
  ganache-volume:
    driver: local