version: '3.7'

services:
  # Blockchain simulator
  ganache-cli:
    build:
      context: ../ganache-cli
    volumes:
      - ganache-volume:/ganache-data
    ports:
      - 8545:8545
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: "loki:3100/loki/api/v1/push"

  rabbitmq:
    image: rabbitmq:3.7.3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  # Blockchain-interactor microservice
  blockchain-interactor:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../blockchain-interactor
    volumes:
      - ../blockchain-interactor:/app
    ports:
      - "9229:9229"
      - "3000:3000"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"

  blockchain-interactor-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - blockchain-interactor-mongo-volume:/data/db
    ports:
      - "27017:27017"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"

volumes:
  blockchain-interactor-mongo-volume:
    driver: local
  ganache-data:
    driver: local