version: '3.7'

services:
  message-broker:
    build:
      dockerfile: dockerfile
      context: ../message-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main_network

  # Inventory microservice
  inventory:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../inventory
    volumes:
      - ../inventory:/app
    ports:
      - "9232:9232"
      - "3002:3002"
    env_file:
      - ../inventory/.env.development # TODO: improve this
    networks:
      - main_network
      - inventory_network
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"

  inventory-data-persistence:
    build:
      dockerfile: dockerfile
      context: ../data-persistence
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=blockcovid
    volumes:
      - inventory-mongo-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - inventory_network
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"


  # Blockchain-interactor microservice
  blockchain-interactor:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../blockchain-interactor
    volumes:
      - ../blockchain-interactor:/app
    ports:
      - "9231:9231"
      - "3001:3001"
    env_file:
      - ../blockchain-interactor/.env.development # TODO: improve this
    networks:
      - main_network
      - blockchain-interactor_network
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"

  blockchain-interactor-data-persistence:
    build:
      dockerfile: dockerfile
      context: ../data-persistence
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=blockcovid
    volumes:
      - blockchain-interactor-mongo-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - blockchain-interactor_network
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"



  # API Gateway
  api-gateway:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../api-gateway-dummy
    volumes:
      - ../api-gateway-dummy:/app
    ports:
      - "9230:9230"
      - "3000:3000"
    networks:
      - main_network
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "loki:3100/loki/api/v1/push"


  # Web Interface
  web-interface:
    build:
      dockerfile: docker/dockerfile.develop
      context: ../web-interface
    volumes:
      - ../web-interface/:/app/
    ports:
      - "4200:4200"
    networks:
      - main_network

networks:
  main_network:
    name: main_network
  blockchain-interactor_network:
    name: blockchain-interactor_network
  inventory_network:
    name: inventory_network

volumes:
  blockchain-interactor-mongo-volume:
    driver: local
  inventory-mongo-volume:
    driver: local
