baseURL = "http://localhost"
title = "Sweleven - Manuale Utente v1.0.0"
theme = "hugo-geekdoc"

pluralizeListTitles = true

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9